#!/usr/bin/env python

import argparse
from slsdet import Eiger
import subprocess
from pathlib import Path
parser = argparse.ArgumentParser()
parser.add_argument("n_frames", type = int)
args = parser.parse_args()

d = Eiger()
d.stopDetector()
d.stopReceiver()

d.fwrite = True
d.frames = args.n_frames

fpath = Path(d.fpath)/f'{d.fname}_master_{d.findex}.raw'

d.acquire()

#convert to hdf5 and add gap pixelss
subprocess.run(['raw2hdf5', fpath.as_posix(), fpath/'hdf5'])

